/*
-- Query: SELECT * FROM henry_viii.answer_table
LIMIT 0, 1000

-- Date: 2026-04-23 01:33
*/
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (1,1,'Anne Boleyn',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (2,1,'Katherine Parr',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (3,1,'Anne of Cleves',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (4,1,'Catherine Howard',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (5,2,'1510',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (6,2,'1509',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (7,2,'1534',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (8,2,'1527',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (9,3,'Anne Cleves',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (10,3,'Anne Boleyn',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (11,3,'Katherine Parr',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (12,3,'Katherine of Aragon',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (13,4,'Katherine of Aragon',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (14,4,'Anne of Cleves',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (15,4,'Katherine Parr',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (16,4,'Jane Seymour',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (17,5,'Catherine Howard',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (18,5,'Katherine Parr',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (19,5,'Anne of Cleves',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (20,5,'Anne Boleyn',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (21,6,'Anne Boleyn',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (22,6,'Katherine of Aragon',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (23,6,'Anne of Cleves',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (24,6,'Catherine Howard',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (25,7,'Catherine Howard',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (26,7,'Katherine of Aragon',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (27,7,'Anne of Cleves',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (28,7,'Jane Seymour',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (29,8,'Arthur, Prince of Wales',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (30,8,'Henry VIII',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (31,8,'Charles V, King of Spain',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (32,8,'Philip II, King of Spain',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (33,9,'Mary I',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (34,9,'Elizabeth I',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (35,9,'Victoria',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (36,9,'Mary II',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (37,10,'Anne',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (38,10,'Mary II',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (39,10,'Mary I',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (40,10,'Elizabeth I',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (41,11,'Anne of Cleves',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (42,11,'Bessie Blount',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (43,11,'Mary Boleyn',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (44,11,'Anne Boleyn',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (45,12,'Katherine of Aragon',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (46,12,'Margaret Tudor',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (47,12,'Mary Boleyn',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (48,12,'Jane Boleyn',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (49,13,'Bessie Blount',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (50,13,'Mary Tudor',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (51,13,'Jane Seymour',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (52,13,'Margaret Tudor',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (53,14,'Katherine Parr',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (54,14,'Bessie Blount',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (55,14,'Mary II',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (56,14,'Anne of Cleves',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (57,15,'Archbishop Thomas Cranmer',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (58,15,'Archbishop William Warham ',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (59,15,'Cardinal Wolsey',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (60,15,'Cardinal Campeggio',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (61,16,'1509',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (62,16,'1521',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (63,16,'1533',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (64,16,'1536',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (65,17,'Thomas Cranmer',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (66,17,'Thomas More',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (67,17,'Cardinal Wolsey',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (68,17,'Thomas Cromwell',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (69,18,'Lord Latimer',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (70,18,'Henry VIII',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (71,18,'Thomas Seymour',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (72,18,'Baron Edward de Burgh',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (73,19,'Philip II',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (74,19,'Francis I',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (75,19,'Edward VI',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (76,19,'Charles V',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (77,20,'Thomas Culpeper',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (78,20,'Francis Derham',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (79,20,'Henry Manox',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (80,20,'John Lascelles',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (81,21,'Anne Boleyn',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (82,21,'Jane Boleyn',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (83,21,'Mary Lascelles',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (84,21,'Agnes Howard',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (85,22,'Henry VIII',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (86,22,'Thomas Seymour',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (87,22,'Lord Latimer',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (88,22,'Baron Edward de Burgh',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (89,23,'1547',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (90,23,'1536',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (91,23,'1542',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (92,23,'1525',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (93,24,'Guilford Dudley',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (94,24,'Mary I',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (95,24,'Jane Grey',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (96,24,'Elizabeth I',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (97,25,'Philip II of Spain',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (98,25,'Charles V of Spain',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (99,25,'Francis I of France',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (100,25,'Louis XII of France',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (101,26,'Henry VII',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (102,26,'Elizabeth I',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (103,26,'Mary I',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (104,26,'Edward VI',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (105,27,'Sir Walter Raleigh',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (106,27,'Philip II, King of Spain',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (107,27,'Sir Robert Cecil',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (108,27,'Lord Robert Dudley',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (109,28,'Philip Duke of Anjou',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (110,28,'Philip II, King of Spain',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (111,28,'She never married',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (112,28,'James V, King of Scotland',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (113,29,'Catherine Howard',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (114,29,'Mary Queen of Scots',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (115,29,'Lord Robert Devereux ',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (116,29,'Robert Aske',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (117,30,'Philip II, King of Spain',1);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (118,30,'Charles V, King of Spain',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (119,30,'Francis I, King of France',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (120,30,'Louis XII, King of France',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (121,31,'Maryland',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (122,31,'North Carolina',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (123,31,'Georgia',0);
INSERT INTO `` (`answer_id`,`question_id`,`answer`,`correct_ans`) VALUES (124,31,'Virginia',1);
